### ISSUE TITLE
the loss of daeldg

### ISSUE THREAD

**Issue by zhaoxin94** [KaiyangZhou/Dassl.pytorch#1]
https://github.com/KaiyangZhou/Dassl.pytorch/blob/5e83fdce6fb51d8d4fbe0441a016eade2ebda423/dassl/engine/dg/daeldg.py#L124-L131

Hi, I think there is something wrong with the loss in daeldg.py. 

Why the 'loss' is assigned to 0?  This will make the supervised loss be invalid.

**Comment by KaiyangZhou** [comment]
very good spot, thank you

it was a typo when I transferred the private code to here

supposed to be `loss_x` but fixed now
