### ISSUE TITLE
The parameters of ''Evaluation on Heterogeneous DG''

### ISSUE THREAD

**Issue by kevinbro96** [KaiyangZhou/Dassl.pytorch#11]
Hi there! 

In the Evaluation on Heterogeneous DG part of your paper, you evaluate the approach on the cross-dataset person re-identification (re-ID) task. 
Can you share your training parameter about this task, including how to set the optimizer, network and data-preprocessing? 

Thank you very much!

**Comment by KaiyangZhou** [comment]
which paper are you referring to?

the reid code can be found at https://github.com/KaiyangZhou/deep-person-reid

**Comment by kevinbro96** [comment]
In the Evaluation on Heterogeneous DG section of your paper DASSL, you did a experiment on  cross-dataset person re-identification (re-ID) task.
Can you share the parameter about this experiment?  https://github.com/KaiyangZhou/deep-person-reid does not have DASSL.

**Comment by KaiyangZhou** [comment]
hmm, I'm a bit confused

do you mean this paper https://arxiv.org/abs/2003.07325 (which introduced the DASSL code)? it doesn't include the reid experiments

**Comment by kevinbro96** [comment]
I mean your AAAI2020 paper DAAIG https://arxiv.org/pdf/2003.06054.pdf. In the Evaluation on Heterogeneous DG section, you did a experiment on cross-dataset person re-identification (re-ID) task.

**Comment by KaiyangZhou** [comment]
the optimization parameters:
```python
lr: 0.001
batch: 32
epoch: 150
stepsize: 60
fixbase: 10
```

the method's hyper-parameters:
```python
lmda: 0.1 (this needs to be tuned; recommended values [0.01, 0.05, 0.1, 0.3, 0.5, 0.7])
alpha: 0.5
warmup: 0
```

**Comment by kevinbro96** [comment]
Thank you very much!
Moreover, I want to ask how to set the data parameter. Should I set INPUT.PIXEL_MEAN = [0.485, 0.456, 0.406] and INPUT.PIXEL_STD = [0.229, 0.224, 0.225]?

**Comment by KaiyangZhou** [comment]
try this first
```python
INPUT.PIXEL_MEAN = [0., 0., 0.]
INPUT.PIXEL_STD = [1., 1., 1.]
```

**Comment by kevinbro96** [comment]
Thank you very much. I will try it.
But I am confused. Because Torch.ToTensor() will turn input images to the range of (0,1), but then you will turn the images to (-1, 1) with INPUT.PIXEL_MEAN = [0., 0., 0.] and INPUT.PIXEL_STD = [1., 1., 1.].
So waht does this mean?

**Comment by KaiyangZhou** [comment]
using zero mean and unit variance is just to keep the value range unchanged, i.e. within [0, 1]
