### ISSUE TITLE
The inconsistency between results after saving and loading model

### ISSUE THREAD

**Issue by KongMingxi** [KaiyangZhou/Dassl.pytorch#15]
Hi there,

Thanks for your code. There is an issue when testing on the saved model.

I run the testing soon after training and the testing result is good. However, when I loaded the saved model to run the testing again, the result is very low. 

How can I get the consistent testing results?

**Comment by KaiyangZhou** [comment]
Can you provide the commands (both training and test) so I can have a look into what's going on?

**Comment by KongMingxi** [comment]
> Can you provide the detailed commands (both training and test) so I can have a look into what's going on?

Thanks for your reply. I'm sorry for making a mistake about something. I have addressed it.

**Comment by KaiyangZhou** [comment]
Glad you have solved the problem.

Btw, if you found anything in the code that could cause confusion, please let me know so I can improve it.

**Comment by KongMingxi** [comment]
> Glad you have solved the problem.
> 
> Btw, if you found anything in the code that could cause confusion, please let me know so I can improve it.

OK, I will let you know if I find any issues.

Thanks again for your help.
