### ISSUE TITLE
Cannot reproduce Vanilla on Office-Home

### ISSUE THREAD

**Issue by c1enyang** [KaiyangZhou/Dassl.pytorch#16]
Thanks for your code.

I have tried to reproduce the Vanilla model (Resnet-18) on Office-Home dataset. I got 47.2% on Clipart, which is far away from the proposed results (49.4%) in your paper.

Can you share your training parameter about this task, including how to set the optimizer, network and data-preprocessing?

**Comment by KaiyangZhou** [comment]
Please try this
```python
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'
```
and let me know the results

**Comment by KaiyangZhou** [comment]
@c1enyang Hi, did you reproduce the results of Vanilla?

**Comment by KaiyangZhou** [comment]
I assume this issue has been resolved.

Closed for now.

**Comment by Claydon-Wang** [comment]
Thanks for your code.

It seems LR_SCHEDULER: 'cosine' is not suitable for PACS or OFFICE-HOME. I run the default setup and I get the results on OFFICE-HOME as below:

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: "sgd"
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"


Artistic | Clipart | Product | Real World | avg
-- | -- | -- | -- | --
58.5 | 47.3 | 73.4 | 74.4 | 63.4
59.5 | 48.1 | 74.3 | 74.9 | 64.2

The results are lower than reported vanilla results. I use setup in DDAIG and get promising vanilla results as below:

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: "sgd"
  LR: 5e-4
  STEPSIZE: [20]
  MAX_EPOCH: 50
  GAMMA: 0.1



Artistic | Clipart | Product | Real World | avg
-- | -- | -- | -- | --
59.5 | 50.3 | 73.7 | 76.1 | 64.9
57.4 | 49.3 | 74.2 | 75.7 | 64.2
58.2 | 49.1 | 74.6 | 76.2 | 64.5
59.8 | 51.7 | 74 | 75.8 | 65.3
60.7 | 50.9 | 74.9 | 75.7 | 65.6
59.2 | 51.2 | 75.2 | 76.3 | 65.5

The similar results can be found on PACS.

**Comment by KaiyangZhou** [comment]
have you tried setting batch size to 32, which I remember is typically the default setting?

**Comment by Claydon-Wang** [comment]
Thx for your kind reminder!
It seems batch size 32 can generate better results.


batch_size | Artistic | Clipart | Product | Real World | avg
-- | -- | -- | -- | -- | --
16 | 58.5 | 47.3 | 73.4 | 74.4 | 63.4
  | 59.5 | 48.1 | 74.3 | 74.9 | 64.2
32 | 59.7 | 50.6 | 75.4 | 76.8 | 65.6
  | 58.7 | 48.6 | 74.3 | 75.6 | 64.3
  | 58.1 | 51.0 | 75.1 | 75.9 | 65.0

Compared with reported vanilla results:

Artistic | Clipart | Product | Real World | avg
-- | -- | -- | -- | --
58.9 | 49.4 | 74.3 | 76.2 | 64.7



</html>
