### ISSUE TITLE
Where is the dataloader module ? I want to find the weak aug & strong aug in your code

### ISSUE THREAD

**Issue by weiyikang** [KaiyangZhou/Dassl.pytorch#18]
I'm very interested in your implementation of weak augmentation & strong augmentation for unlabeled data, while I can't find the dataloader and transform module in your code.

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/Dassl.pytorch/tree/master/dassl/data

https://github.com/KaiyangZhou/Dassl.pytorch/tree/master/dassl/data/transforms

**Comment by weiyikang** [comment]
Thanks for your guidence!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 上午10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KaiyangZhou/Dassl.pytorch] Where is the dataloader module ? I want to find the weak aug &amp; strong aug in your code (#18)





 
https://github.com/KaiyangZhou/Dassl.pytorch/tree/master/dassl/data
 
https://github.com/KaiyangZhou/Dassl.pytorch/tree/master/dassl/data/transforms
