### ISSUE TITLE
There are some question about this code

### ISSUE THREAD

**Issue by buerzlh** [KaiyangZhou/Dassl.pytorch#2]
This code is a very good job, but in the process of my study, I found some problems, so I hope the author can help me to solve them.

**Comment by buerzlh** [comment]
In File "Dassl.pytorch/dassl/data/datasets/base_dataset.py", line 25: assert check_isfile(impath),
I think this maybe wrong, do it need to check folders instead of files?

**Comment by KaiyangZhou** [comment]
`impath` is supposed to contain the path to an image rather than a folder

**Comment by weiliuxm** [comment]
> In File "Dassl.pytorch/dassl/data/datasets/base_dataset.py", line 25: assert check_isfile(impath),
> I think this maybe wrong, do it need to check folders instead of files?

The path of "class_names" and "class_path" in office31.py may not be right.
There is a subdirectory named "images"  in the directory "domain_dir".

**Comment by KaiyangZhou** [comment]
do a little bit of work by moving all class folders to `domain_dir`

please refer to `DATASET.md`

**Comment by buerzlh** [comment]
This is a very good job, especially when I have carefully debugged M3SDA, but I have a question about how you can sample as much data as possible for each source domain in a dataset with multiple source domains I think this is not an accident because a _**split_bach**_ is clearly pointed out in your code. Thank you very much.

**Comment by buerzlh** [comment]
And there is another problem, because the data of each source domain is not the same. When all the data of the source domain are collected into one data set, when sampling the same data of each source domain, will there be no data available for sampling in the source domain with less data?

**Comment by KaiyangZhou** [comment]
@buerzlh please refer to https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/samplers.py#L7

**Comment by buerzlh** [comment]
OK, i got it. Thank you very much.
