### ISSUE TITLE
How to train using MME

### ISSUE THREAD

**Issue by shreejalt** [KaiyangZhou/Dassl.pytorch#28]
I want to train on my custom dataset using MME. Can you guide me in that?

**Comment by KaiyangZhou** [comment]
You can take a look at other projects that are based on Dassl, like these
- https://github.com/KaiyangZhou/CoOp
- https://github.com/KaiyangZhou/ssdg-benchmark

To write a new dataset class, see this https://github.com/KaiyangZhou/Dassl.pytorch#add-a-dataset
