### ISSUE TITLE
How to run benchmarks

### ISSUE THREAD

**Issue by weiliuxm** [KaiyangZhou/Dassl.pytorch#3]
Hello  Kaiyang,
thank you for sharing the codes.

Is there any guide to run benchmarks such as MME, MCD, et al.
Many thanks for your reply.

**Comment by KaiyangZhou** [comment]
You can do
```bash
CUDA_VISIBLE_DEVICES=0 python tools/train.py \
--root $DATA \
--trainer MME \
--source-domains amazon \
--target-domains webcam \
--dataset-config-file configs/datasets/da/office31.yaml \
--config-file configs/trainers/da/source_only/office31.yaml \
--output-dir output/mme_office31_amazon2webcam \
TRAINER.MME.LMDA 0.1
```

Or create a cfg file specific for MME/MCD

See [here](https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/config/defaults.py) for method-specific parameters

I'll add a more detailed instruction in the near future (let me know if you have any suggestions)

**Comment by weiliuxm** [comment]
Thank you.
