### ISSUE TITLE
confusion matrix

### ISSUE THREAD

**Issue by zhaoxin94** [KaiyangZhou/Dassl.pytorch#31]
https://github.com/KaiyangZhou/Dassl.pytorch/blob/08acfb386edd765c6a4c12b7b7f50dfa113d9c82/dassl/evaluation/evaluator.py#L42-L46

I think we should also reset the self._y_true and self._y_pred in the reset function.
Otherwise we'll get wrong confusion matrix.

**Comment by KaiyangZhou** [comment]
Thanks. I've fixed the error.
