### ISSUE TITLE
Where is the definition of "trainer.train()"? Thank you .

### ISSUE THREAD

**Issue by Learn2Ln** [KaiyangZhou/Dassl.pytorch#4]
In /tools/train.py, line 89, "trainer.train()".
For example， trainer= ‘DDAIG’，
Where is the definition of "trainer.train()"? Thank you  very much.
Maybe I am confused about the code in "dassl/engine/bulid.py"。

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/engine/trainer.py#L215
