### ISSUE TITLE
Issue with FixMatch training on customs datasets

### ISSUE THREAD

**Issue by ghost** [KaiyangZhou/Dassl.pytorch#51]
Hello, I am having trouble training FixMatch with custom datasets.
I got this error:
`input_x2 = batch_x["img2"]
KeyError: 'img2`.

As part of the config/trainer files, I set K_TRANSFORMS to 2. When DatasetWrapper.__getitem__() is called, it returns one image.

**Comment by KaiyangZhou** [comment]
what's the command to reproduce the error?

**Comment by EmanAli91** [comment]
I don't know what happend but it is solved when I modifed this line in `parse_batch_train`
`input_x = batch_x["img"][0].to(self.device)]`

**Comment by ghost** [comment]
I just use your fixmatch implementation with dassl and integrated in my code. The same implementation for cdac.py worked for me like that
`input_x = batch_x["img"][0]`
but the fixmmatch did not.

**Comment by KaiyangZhou** [comment]
I'm a bit rusty on the part where this error could be triggered. I'd suggest you take a look at this code https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/data_manager.py#L220 where you might find the answer. Thanks

**Comment by EmanAli91** [comment]
I think I've figured out the problem. 
I set `DATALOADER.K_TRANSFORMS = 2`, but it should be `DATALOADER.K_TRANSFORMS = 1`.
Thank you for your help.

**Comment by ghost** [comment]
I think I've figured out the problem. 
I set `DATALOADER.K_TRANSFORMS = 2`, but it should be `DATALOADER.K_TRANSFORMS = 1`.
Thank you for your help.
