### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by lvpeng159** [KaiyangZhou/Dassl.pytorch#56]
Loading evaluator: Classification
Traceback (most recent call last):
  File "tools/train.py", line 191, in <module>
    main(args)
  File "tools/train.py", line 110, in main
    trainer.load_model(args.model_dir, epoch=args.load_epoch)
  File "d:\coop-main\dassl.pytorch-master\dassl\engine\trainer.py", line 199, in load_model
    f"Load {checkpoint} to {name} (epoch={epoch}, val_result={val_result:.1f})"
TypeError: unsupported format string passed to NoneType.__format__

terminal input:python tools/train.py --root datasets/da/ --trainer SourceOnly --dataset-config-file configs/datasets/da/visda17.yaml --config-file configs/trainers/da/source_only/visda17.yaml --output-dir output/office31_test --source-domains real --target-domains real --eval-only --model-dir output/office31 --load-epoch 2

when i used .pth to test dataset, which occured this matter,help me plz

**Comment by lvpeng159** [comment]
i have resolved this problem

**Comment by lvpeng159** [comment]
hey,it is my pleasure to help you solve bug,the answer which you need in the picture



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 22, 2023 16:05 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [KaiyangZhou/Dassl.pytorch] TypeError: unsupported format stringpassed to NoneType.__format__ (Issue #56)




 
Hi, thanks for your sharing, I encountered this problem today when I first tried to run vanilla model on the pacs dataset. How you fixed this error? Thanks.

**Comment by Jordan-Liao** [comment]
> i have resolved this problem
Hi, I also encountered the same problem, how did you solve it?
Traceback (most recent call last):
  File "/home/storageSDA1/liaojr/Dassl.pytorch/tools/train.py", line 191, in <module>
    main(args)
  File "/home/storageSDA1/Dassl.pytorch/tools/train.py", line 110, in main
    trainer.load_model(args.model_dir, epoch=args.load_epoch)
  File "/home/storageSDA1/Dassl.pytorch/dassl/engine/trainer.py", line 199, in load_model
    f"Load {model_path} to {name} (epoch={epoch}, val_result={val_result:.1f})"
TypeError: unsupported format string passed to NoneType.__format__
