### ISSUE TITLE
question about 'not file found'

### ISSUE THREAD

**Issue by inspire-lts** [KaiyangZhou/Dassl.pytorch#7]
Thank you share your code! I am a beginner . I ran office31 dataset, showed file not found. But I have this file.
![](https://gitee.com/new_lts/MyImages/raw/master/img/20200712041505.png)
And my sturcture list:
![](https://gitee.com/new_lts/MyImages/raw/master/img/20200712041757.png)
![](https://gitee.com/new_lts/MyImages/raw/master/img/20200712042343.png)

**Comment by KaiyangZhou** [comment]
you need to move all files out of `images/`, see this for the file structure https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/DATASETS.md#office-31

**Comment by inspire-lts** [comment]
@KaiyangZhou Thank you very much! Sorry, I didn't look at the file structure carefully. Cool code!
