### ISSUE TITLE
Files not found for DAEL Digits5

### ISSUE THREAD

**Issue by pmirallesr** [KaiyangZhou/Dassl.pytorch#8]
Hello,

I replicated the dataset folder structure and tried running DAEL on digit5. However, it cannot find the mnist files, and seems to be searching for the wrong files. Upon closer inspection the load_mnist function in /data/datasets/da/digit5.py seems to expect different files from those provided in the links in DATASETS.md. Is it possible that this file is outdated with respect to the readme?

**Comment by Learn2Ln** [comment]
How did you run the training code for DAEL?

When I ran the DAEL like this ,
CUDA_VISIBLE_DEVICES=5 python tools/train.py \
--root /data2/datasets/visda2019 \
--trainer DAEL \
--source-domains clipart product art sketch quickdraw \
--target-domains real \
--dataset-config-file configs/datasets/da/domainnet.yaml \
--config-file configs/trainers/da/m3sda/domainnet.yaml \
--output-dir output/DomNet1

it raise an error" File "/data1/Dassl.pytorch/dassl/engine/da/dael.py", line 51, in check_cfg
    assert len(cfg.TRAINER.DAEL.STRONG_TRANSFORMS) > 0
AssertionError
"...
Thank you very much.
Best wishes!
